name: Workflow-Pipeline
on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - "*"

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          mkdir build
          go test ./... -v -coverprofile build/coverage.out -coverpkg=./...
          go tool cover -func build/coverage.out

  code_quality:
    name: Code Quality
    runs-on: ubuntu-latest
    container: "golangci/golangci-lint:v1.43.0"
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          git config --global url."https://${{ secrets.PAT}}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global http.sslVerify false
          go get -v -t -d ./...
      - name: GolangCI-Lint
        run: |
          golangci-lint run --timeout 5m0s
